### ISSUE TITLE
Error trying to execute readStatusRegister(): Wrong CRC found 

### ISSUE THREAD

**Issue by LabtronicsDesign** [Sensirion/arduino-i2c-sht3x#2]
I am recieving this error message using the example sketch. I am not sure if I have done anything wrong as it's copied and pasted into my program.

Sensor: SHT30A
Platform: Arduino IDE
Board: ESP32-S3

`Error trying to execute readStatusRegister(): Wrong CRC found`

**Comment by LeonieFierz** [comment]
Hi @LabtronicsDesign 

Thank you for contacting us.
The CRC error could be due to a weak or instable connection between your sensor and the board. Please make sure that SDA and SCL cables are well plugged in. 

Best, Léonie

**Comment by LabtronicsDesign** [comment]
Hi this isn’t the case as I have various Sensirion sensors attached on the same I2C bus. All the other sensors work perfectly just this particular one has issues

**Comment by LeonieFierz** [comment]
We see this error as well when there is an interference or other disturbance on the I2C Bus. If possible, please try with just the SHT30A sensor connected. If you have a logic analyzer at hand you could check the I2C signal.
